window.$ = jQuery;
import { initStatsCounter } from "./stat-ticker.js";
import { initAccordions } from "./accordion";
import { navVisibility } from "./nav.js";
import { initHoverImageCursor } from "./image-cursor.js";
import { initSwipers } from "./swiper";
import { simpleFilterData, masonryFilterData } from "./filter.js";
import { initMasonary } from "./masonary.js";
import { initHamburger } from "./hamburger.js";
import { initVideos } from "./video.js";
import { initPortraitVideoModal } from "./portrait-video-modal.js";
import { initAjaxFilter } from "./ajax.js";
// import AOS from 'aos';
$(document).ready(function () {
  masonryFilterData();
  simpleFilterData();
  initAccordions();
  initStatsCounter();
  initHoverImageCursor();
  navVisibility();
  initSwipers();
  initMasonary();
  initHamburger();
  initVideos();
  initPortraitVideoModal();
  initAjaxFilter();
});
